[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'sha256-8ZgGo/nOlaDknQkDUYiedLuFRSGJwIz6LAzsOrNxhmU=' https://checkout.razorpay.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://ecommerce-server-1cz2.onrender.com https://api.postalpincode.in https://lumberjack.razorpay.com https://o4509372423667712.ingest.us.sentry.io; img-src 'self' https://res.cloudinary.com data: blob:; font-src 'self' https://fonts.gstatic.com; frame-src https://api.razorpay.com https://checkout.razorpay.com; frame-ancestors 'none'; report-uri https://o4509372423667712.ingest.us.sentry.io/api/4509372426289152/security/?sentry_key=e583d3ab8774cd7d61d3c65e3db10118; report-to https://o4509372423667712.ingest.us.sentry.io/api/4509372426289152/security/?sentry_key=e583d3ab8774cd7d61d3c65e3db10118;"

    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200