// export const loginConstants = {
//     LOGIN_REQUEST: "LOGIN_REQUEST",
//     LOGIN_SUCCESS: "LOGIN_SUCCESS",
//     LOGIN_FAIL: "LOGIN_FAIL",
// }

// export const logoutConstants = {
//     LOGOUT_REQUEST: "LOGOUT_REQUEST",
//     LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
//     LOGOUT_FAIL: "LOGOUT_FAIL"
// }

// export const signupConstants = {
//     SIGNUP_REQUEST: "SIGNUP_REQUEST",
//     SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
//     SIGNUP_FAIL: "SIGNUP_FAIL",
// }

// export const userProfileConstants = {
//     GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
//     GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
//     GET_USER_PROFILE_FAIL: "GET_USER_PROFILE_FAIL",

//     UPDATE_USER_PROFILE_PIC_SUCCESS: "UPDATE_USER_PROFILE_PIC_SUCCESS",
//     UPDATE_USER_PROFILE_PIC_FAIL: "UPDATE_USER_PROFILE_PIC_FAIL",

//     UPDATE_USER_PROFILE_DETAIL_SUCCESS: "UPDATE_USER_PROFILE_DETAIL_SUCCESS",
//     UPDATE_USER_PROFILE_DETAIL_FAIL: "UPDATE_USER_PROFILE_DETAIL_FAIL"
// }

// export const categoryConstants = {
//     GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
//     GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
//     GET_CATEGORY_FAIL: "GET_CATEGORY_FAIL"
// }

// export const productConstants = {
//     GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
//     GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
//     GET_ALL_PRODUCT_FAIL: "GET_ALL_PRODUCT_FAIL",

//     GET_SINGLE_PRODUCT_REQUEST: "GET_SINGLE_PRODUCT_REQUEST",
//     GET_SINGLE_PRODUCT_SUCCESS: "GET_SINGLE_PRODUCT_SUCCESS",
//     GET_SINGLE_PRODUCT_FAIL: "GET_SINGLE_PRODUCT_FAIL",

//     GET_FEATURED_PRODUCT_SUCCESS: "GET_FEATURED_PRODUCT_SUCCESS",
//     GET_FEATURED_PRODUCT_FAIL: "GET_FEATURED_PRODUCT_FAIL"

// }

// export const bannerConstant = {
//     GET_BANNER_REQUEST: "GET_BANNER_REQUEST",
//     GET_BANNER_SUCCESS: "GET_BANNER_SUCCESS",
//     GET_BANNER_FAIL: "GET_BANNER_FAIL",
// }

// export const cartConstant = {
//     ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
//     ADD_TO_CART_FAIL: "ADD_TO_CART_FAIL",

//     GET_ITEM_FROM_CART_SUCCESS: "GET_ITEM_FROM_CART_SUCCESS",
//     GET_ITEM_FROM_CART_FAIL: "GET_ITEM_FROM_CART_SUCCESS",

//     REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
//     REMOVE_CART_ITEM_FAIL: "REMOVE_CART_ITEM_FAIL",

//     REMOVE_CART_ITEM_FROM_STATE: "REMOVE_CART_ITEM_FROM_STATE"
// }

// export const messageConstants = {
//     REMOVE_LOGIN_ERROR: "REMOVE_LOGIN_ERROR",
//     REMOVE_CART_MESSAGE: "REMOVE_CART_MESSAGE"
// }

// export const userAddressConstant = {
//     ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
//     ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",

//     GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
//     GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",

//     DELETE_USER_ADDRESS_SUCCESS: "DELETE_USER_ADDRESS_SUCCESS",
//     DELETE_USER_ADDRESS_FAILURE: "DELETE_USER_ADDRESS_FAILURE",

//     REMOVE_ADDRESS_MESSAGE_ERROR: "REMOVE_ADDRESS_MESSAGE_ERROR"
// }

// export const userOrderConstant = {
//     ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
//     ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
//     ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",

//     GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
//     GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
//     GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE"
// }
